name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 6 * * *'
    # scheduled for 6:00 UTC every day, 1 AM ET now

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: nytimes/covid-19-data      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master        # set the branch to merge to
