name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: "0 7 * * *"  
    # scheduled for 7:00 UTC every day, currently 2 AM ET

jobs:
  merge-from-upstream-remote:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master                           # set the branch to merge to
          fetch-depth: 0                        # get all changes
          
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          username: discdiver                  # set the username for git commit
          useremail: jeffmshale@gmail.com      # set the email for git commit
          upstream: nytimes/covid-19-data      # set the upstream repo
          upstream-branch: master              # set the upstream branch to merge from
          branch: master                       # set the branch to merge to
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
