name: manual merge
on: 
  workflow_dispatch:
    inputs:
      upstream: 
        required: true
        description: "the upstream repo as user/repo"
        default: "nytimes/covid-19-data"
      upstream-branch: 
        description: "the branch name in the target repo to merge from"
        required: true
        default: 'master'           
      branch: 
        description: 'the branch name in your repo to merge into'
        required: true
        default: 'master'         
      useremail: 
        description: "the email address - required for git commit"
        default: 'jeffmshale@gmail.com'
        required: true
      username: 
        description: "the username - required for git commit"
        default: 'discdiver'
        required: true

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: ${{ github.event.inputs.useremail}}
          username: ${{ github.event.inputs.username}}
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream-branch }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}
